# Version and package destination
# -------------------------------
version=4.2.5
version.full=${version}.${current.build.number}
pkg.dir=/Users/phollema/Documents/Work/NOAA/CoastWatch Utilities/Packages
install.dir=/Applications/CoastWatch Utilities 4.2.0

# Supplemental tools
# ------------------
install4j.dir=/Applications/install4j.app/Contents/Resources/app
password.file=/Users/phollema/Documents/Work/Terrenus/Code Signing/password.properties

# Default look and feel
# ---------------------
default.laf=mac

# Native library path
# -------------------
ld.var=DYLD_LIBRARY_PATH
#os.libs=macosx_x86
os.libs=macosx_x86_64

# Testing VM args
# ---------------
vm.args=-Xmx2048m -Dcw.cache.size=512 -Dcom.sun.management.jmxremote -Djava.util.logging.config.class=noaa.coastwatch.tools.LoggingConfig
test.debug.args=-Dcw.debug=fine

# Extra Javac arguments (platform-specific)
# -----------------------------------------
#javac.args=--source 11 --target 11
javac.args=--release 11
