/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noaa_coastwatch_io_CWF */

#ifndef _Included_noaa_coastwatch_io_CWF
#define _Included_noaa_coastwatch_io_CWF
#ifdef __cplusplus
extern "C" {
#endif
#undef noaa_coastwatch_io_CWF_CW_BYTE
#define noaa_coastwatch_io_CWF_CW_BYTE 0L
#undef noaa_coastwatch_io_CWF_CW_CHAR
#define noaa_coastwatch_io_CWF_CW_CHAR 1L
#undef noaa_coastwatch_io_CWF_CW_SHORT
#define noaa_coastwatch_io_CWF_CW_SHORT 2L
#undef noaa_coastwatch_io_CWF_CW_FLOAT
#define noaa_coastwatch_io_CWF_CW_FLOAT 3L
#undef noaa_coastwatch_io_CWF_CW_CLOBBER
#define noaa_coastwatch_io_CWF_CW_CLOBBER 0L
#undef noaa_coastwatch_io_CWF_CW_NOCLOBBER
#define noaa_coastwatch_io_CWF_CW_NOCLOBBER 1L
#undef noaa_coastwatch_io_CWF_CW_NOWRITE
#define noaa_coastwatch_io_CWF_CW_NOWRITE 0L
#undef noaa_coastwatch_io_CWF_CW_WRITE
#define noaa_coastwatch_io_CWF_CW_WRITE 1L
#undef noaa_coastwatch_io_CWF_UNMAPPED
#define noaa_coastwatch_io_CWF_UNMAPPED 0L
#undef noaa_coastwatch_io_CWF_MERCATOR
#define noaa_coastwatch_io_CWF_MERCATOR 1L
#undef noaa_coastwatch_io_CWF_POLAR
#define noaa_coastwatch_io_CWF_POLAR 2L
#undef noaa_coastwatch_io_CWF_LINEAR
#define noaa_coastwatch_io_CWF_LINEAR 3L
#undef noaa_coastwatch_io_CWF_NORTH
#define noaa_coastwatch_io_CWF_NORTH 1L
#undef noaa_coastwatch_io_CWF_SOUTH
#define noaa_coastwatch_io_CWF_SOUTH -1L
#undef noaa_coastwatch_io_CWF_EARTH_RADIUS
#define noaa_coastwatch_io_CWF_EARTH_RADIUS 6371.2
#undef noaa_coastwatch_io_CWF_CW_BADVAL
#define noaa_coastwatch_io_CWF_CW_BADVAL -999.0f
/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    create
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_create
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    enddef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_enddef
  (JNIEnv *, jclass, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    define_dimension
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_define_1dimension
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_dimension_id
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1dimension_1id
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_dimension_length
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1dimension_1length
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_dimension_name
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_noaa_coastwatch_io_CWF_inquire_1dimension_1name
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    define_variable
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_define_1variable
  (JNIEnv *, jclass, jint, jstring, jintArray);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_variable_id
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1variable_1id
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_variable_name
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_noaa_coastwatch_io_CWF_inquire_1variable_1name
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_variable_type
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1variable_1type
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_variable_attributes
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1variable_1attributes
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_variable_dimension_ids
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_noaa_coastwatch_io_CWF_inquire_1variable_1dimension_1ids
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    put_variable
 * Signature: (II[I[I[[F)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_put_1variable__II_3I_3I_3_3F
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jobjectArray);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    put_variable
 * Signature: (II[I[I[[B)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_put_1variable__II_3I_3I_3_3B
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jobjectArray);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_variable_float
 * Signature: (II[I[I)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_noaa_coastwatch_io_CWF_get_1variable_1float
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_variable_byte
 * Signature: (II[I[I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_noaa_coastwatch_io_CWF_get_1variable_1byte
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_attribute_name
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_noaa_coastwatch_io_CWF_inquire_1attribute_1name
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_attribute_type
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1attribute_1type
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_attribute_num
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1attribute_1num
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    inquire_attribute_id
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_noaa_coastwatch_io_CWF_inquire_1attribute_1id
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_attribute_string
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_noaa_coastwatch_io_CWF_get_1attribute_1string
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_attribute_float
 * Signature: (IILjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_noaa_coastwatch_io_CWF_get_1attribute_1float
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_attribute_short
 * Signature: (IILjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_noaa_coastwatch_io_CWF_get_1attribute_1short
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    put_attribute
 * Signature: (IILjava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_put_1attribute__IILjava_lang_String_2S
  (JNIEnv *, jclass, jint, jint, jstring, jshort);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    put_attribute
 * Signature: (IILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_put_1attribute__IILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    put_attribute
 * Signature: (IILjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_put_1attribute__IILjava_lang_String_2F
  (JNIEnv *, jclass, jint, jint, jstring, jfloat);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    init_projection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_CWF_init_1projection
  (JNIEnv *, jclass, jint);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    projection_info
 * Signature: ()Lnoaa/coastwatch/io/CWFProjectionInfo;
 */
JNIEXPORT jobject JNICALL Java_noaa_coastwatch_io_CWF_projection_1info
  (JNIEnv *, jclass);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_latitiude_longitude
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_noaa_coastwatch_io_CWF_get_1latitiude_1longitude
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     noaa_coastwatch_io_CWF
 * Method:    get_pixel
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_noaa_coastwatch_io_CWF_get_1pixel
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
