#!/bin/sh

if [ -z "$1" ] ; then
  echo "Usage: makemac libname"
  exit 1
fi

set -x

pre=lib$1
lib=$pre.jnilib
make arch=ppc
make arch=i386
lipo ${pre}* -create -output $lib
install_name_tool -id $lib $lib

