/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noaa_coastwatch_io_HDFWriter */

#ifndef _Included_noaa_coastwatch_io_HDFWriter
#define _Included_noaa_coastwatch_io_HDFWriter
#ifdef __cplusplus
extern "C" {
#endif
#undef noaa_coastwatch_io_HDFWriter_DEFAULT_CHUNK_SIZE
#define noaa_coastwatch_io_HDFWriter_DEFAULT_CHUNK_SIZE 524288L
/* Inaccessible static: class_00024noaa_00024coastwatch_00024io_00024HDFWriter */
/*
 * Class:     noaa_coastwatch_io_HDFWriter
 * Method:    setChunkCompress
 * Signature: (IZ[I)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_io_HDFWriter_setChunkCompress
  (JNIEnv *, jclass, jint, jboolean, jintArray);

#ifdef __cplusplus
}
#endif
#endif
