/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noaa_coastwatch_io_HDFReader */

#ifndef _Included_noaa_coastwatch_io_HDFReader
#define _Included_noaa_coastwatch_io_HDFReader
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: dataProjection */
/*
 * Class:     noaa_coastwatch_io_HDFReader
 * Method:    getChunkLengths
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_noaa_coastwatch_io_HDFReader_getChunkLengths
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
