/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class noaa_coastwatch_util_GCTP */

#ifndef _Included_noaa_coastwatch_util_GCTP
#define _Included_noaa_coastwatch_util_GCTP
#ifdef __cplusplus
extern "C" {
#endif
#undef noaa_coastwatch_util_GCTP_GEO
#define noaa_coastwatch_util_GCTP_GEO 0L
#undef noaa_coastwatch_util_GCTP_UTM
#define noaa_coastwatch_util_GCTP_UTM 1L
#undef noaa_coastwatch_util_GCTP_SPCS
#define noaa_coastwatch_util_GCTP_SPCS 2L
#undef noaa_coastwatch_util_GCTP_ALBERS
#define noaa_coastwatch_util_GCTP_ALBERS 3L
#undef noaa_coastwatch_util_GCTP_LAMCC
#define noaa_coastwatch_util_GCTP_LAMCC 4L
#undef noaa_coastwatch_util_GCTP_MERCAT
#define noaa_coastwatch_util_GCTP_MERCAT 5L
#undef noaa_coastwatch_util_GCTP_PS
#define noaa_coastwatch_util_GCTP_PS 6L
#undef noaa_coastwatch_util_GCTP_POLYC
#define noaa_coastwatch_util_GCTP_POLYC 7L
#undef noaa_coastwatch_util_GCTP_EQUIDC
#define noaa_coastwatch_util_GCTP_EQUIDC 8L
#undef noaa_coastwatch_util_GCTP_TM
#define noaa_coastwatch_util_GCTP_TM 9L
#undef noaa_coastwatch_util_GCTP_STEREO
#define noaa_coastwatch_util_GCTP_STEREO 10L
#undef noaa_coastwatch_util_GCTP_LAMAZ
#define noaa_coastwatch_util_GCTP_LAMAZ 11L
#undef noaa_coastwatch_util_GCTP_AZMEQD
#define noaa_coastwatch_util_GCTP_AZMEQD 12L
#undef noaa_coastwatch_util_GCTP_GNOMON
#define noaa_coastwatch_util_GCTP_GNOMON 13L
#undef noaa_coastwatch_util_GCTP_ORTHO
#define noaa_coastwatch_util_GCTP_ORTHO 14L
#undef noaa_coastwatch_util_GCTP_GVNSP
#define noaa_coastwatch_util_GCTP_GVNSP 15L
#undef noaa_coastwatch_util_GCTP_SNSOID
#define noaa_coastwatch_util_GCTP_SNSOID 16L
#undef noaa_coastwatch_util_GCTP_EQRECT
#define noaa_coastwatch_util_GCTP_EQRECT 17L
#undef noaa_coastwatch_util_GCTP_MILLER
#define noaa_coastwatch_util_GCTP_MILLER 18L
#undef noaa_coastwatch_util_GCTP_VGRINT
#define noaa_coastwatch_util_GCTP_VGRINT 19L
#undef noaa_coastwatch_util_GCTP_HOM
#define noaa_coastwatch_util_GCTP_HOM 20L
#undef noaa_coastwatch_util_GCTP_ROBIN
#define noaa_coastwatch_util_GCTP_ROBIN 21L
#undef noaa_coastwatch_util_GCTP_SOM
#define noaa_coastwatch_util_GCTP_SOM 22L
#undef noaa_coastwatch_util_GCTP_ALASKA
#define noaa_coastwatch_util_GCTP_ALASKA 23L
#undef noaa_coastwatch_util_GCTP_GOOD
#define noaa_coastwatch_util_GCTP_GOOD 24L
#undef noaa_coastwatch_util_GCTP_MOLL
#define noaa_coastwatch_util_GCTP_MOLL 25L
#undef noaa_coastwatch_util_GCTP_IMOLL
#define noaa_coastwatch_util_GCTP_IMOLL 26L
#undef noaa_coastwatch_util_GCTP_HAMMER
#define noaa_coastwatch_util_GCTP_HAMMER 27L
#undef noaa_coastwatch_util_GCTP_WAGIV
#define noaa_coastwatch_util_GCTP_WAGIV 28L
#undef noaa_coastwatch_util_GCTP_WAGVII
#define noaa_coastwatch_util_GCTP_WAGVII 29L
#undef noaa_coastwatch_util_GCTP_OBEQA
#define noaa_coastwatch_util_GCTP_OBEQA 30L
#undef noaa_coastwatch_util_GCTP_USDEF
#define noaa_coastwatch_util_GCTP_USDEF 99L
#undef noaa_coastwatch_util_GCTP_MAX_PROJECTIONS
#define noaa_coastwatch_util_GCTP_MAX_PROJECTIONS 31L
/* Inaccessible static: PROJECTION_NAMES */
#undef noaa_coastwatch_util_GCTP_RADIAN
#define noaa_coastwatch_util_GCTP_RADIAN 0L
#undef noaa_coastwatch_util_GCTP_FEET
#define noaa_coastwatch_util_GCTP_FEET 1L
#undef noaa_coastwatch_util_GCTP_METER
#define noaa_coastwatch_util_GCTP_METER 2L
#undef noaa_coastwatch_util_GCTP_SECOND
#define noaa_coastwatch_util_GCTP_SECOND 3L
#undef noaa_coastwatch_util_GCTP_DEGREE
#define noaa_coastwatch_util_GCTP_DEGREE 4L
#undef noaa_coastwatch_util_GCTP_INT_FEET
#define noaa_coastwatch_util_GCTP_INT_FEET 5L
#undef noaa_coastwatch_util_GCTP_STPLN_TABLE
#define noaa_coastwatch_util_GCTP_STPLN_TABLE 6L
#undef noaa_coastwatch_util_GCTP_CLARKE1866
#define noaa_coastwatch_util_GCTP_CLARKE1866 0L
#undef noaa_coastwatch_util_GCTP_CLARKE1880
#define noaa_coastwatch_util_GCTP_CLARKE1880 1L
#undef noaa_coastwatch_util_GCTP_BESSEL
#define noaa_coastwatch_util_GCTP_BESSEL 2L
#undef noaa_coastwatch_util_GCTP_INT1967
#define noaa_coastwatch_util_GCTP_INT1967 3L
#undef noaa_coastwatch_util_GCTP_INT1909
#define noaa_coastwatch_util_GCTP_INT1909 4L
#undef noaa_coastwatch_util_GCTP_WGS72
#define noaa_coastwatch_util_GCTP_WGS72 5L
#undef noaa_coastwatch_util_GCTP_EVEREST
#define noaa_coastwatch_util_GCTP_EVEREST 6L
#undef noaa_coastwatch_util_GCTP_WGS66
#define noaa_coastwatch_util_GCTP_WGS66 7L
#undef noaa_coastwatch_util_GCTP_GRS1980
#define noaa_coastwatch_util_GCTP_GRS1980 8L
#undef noaa_coastwatch_util_GCTP_AIRY
#define noaa_coastwatch_util_GCTP_AIRY 9L
#undef noaa_coastwatch_util_GCTP_MOD_EVEREST
#define noaa_coastwatch_util_GCTP_MOD_EVEREST 10L
#undef noaa_coastwatch_util_GCTP_MOD_AIRY
#define noaa_coastwatch_util_GCTP_MOD_AIRY 11L
#undef noaa_coastwatch_util_GCTP_WGS84
#define noaa_coastwatch_util_GCTP_WGS84 12L
#undef noaa_coastwatch_util_GCTP_SE_ASIA
#define noaa_coastwatch_util_GCTP_SE_ASIA 13L
#undef noaa_coastwatch_util_GCTP_AUS_NAT
#define noaa_coastwatch_util_GCTP_AUS_NAT 14L
#undef noaa_coastwatch_util_GCTP_KRASS
#define noaa_coastwatch_util_GCTP_KRASS 15L
#undef noaa_coastwatch_util_GCTP_HOUGH
#define noaa_coastwatch_util_GCTP_HOUGH 16L
#undef noaa_coastwatch_util_GCTP_MERCURY1960
#define noaa_coastwatch_util_GCTP_MERCURY1960 17L
#undef noaa_coastwatch_util_GCTP_MOD_MER1968
#define noaa_coastwatch_util_GCTP_MOD_MER1968 18L
#undef noaa_coastwatch_util_GCTP_SPHERE
#define noaa_coastwatch_util_GCTP_SPHERE 19L
#undef noaa_coastwatch_util_GCTP_MAX_SPHEROIDS
#define noaa_coastwatch_util_GCTP_MAX_SPHEROIDS 20L
/* Inaccessible static: SPHEROID_NAMES */
#undef noaa_coastwatch_util_GCTP_STD_RADIUS
#define noaa_coastwatch_util_GCTP_STD_RADIUS 6370.997
/* Inaccessible static: SPHEROID_SEMI_MAJOR */
/* Inaccessible static: SPHEROID_INV_FLAT */
/* Inaccessible static: SPHEROID_SEMI_MINOR */
#undef noaa_coastwatch_util_GCTP_TERM
#define noaa_coastwatch_util_GCTP_TERM 0L
#undef noaa_coastwatch_util_GCTP_FILE
#define noaa_coastwatch_util_GCTP_FILE 1L
#undef noaa_coastwatch_util_GCTP_BOTH
#define noaa_coastwatch_util_GCTP_BOTH 2L
#undef noaa_coastwatch_util_GCTP_NEITHER
#define noaa_coastwatch_util_GCTP_NEITHER -1L
/* Inaccessible static: reqDesc */
/* Inaccessible static: reqUnits */
/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    gctp
 * Signature: ([DII[DIIILjava/lang/String;ILjava/lang/String;II[DIILjava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_noaa_coastwatch_util_GCTP_gctp
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jint, jstring, jint, jstring, jint, jint, jdoubleArray, jint, jint, jstring, jstring);

/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    init_forward
 * Signature: (II[DILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_util_GCTP_init_1forward
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jint, jstring, jstring);

/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    init_inverse
 * Signature: (II[DILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_noaa_coastwatch_util_GCTP_init_1inverse
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jint, jstring, jstring);

/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    forward
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_noaa_coastwatch_util_GCTP_forward
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    inverse
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_noaa_coastwatch_util_GCTP_inverse
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     noaa_coastwatch_util_GCTP
 * Method:    pakr2dm
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_noaa_coastwatch_util_GCTP_pakr2dm
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
